"""Phase 10.8 — LivePaperRunner: Signal Activation & Debug.

Extends Phase 10.4 with:
  - Signal debug logging per tick (SIGNAL_DEBUG_MODE)
  - Signal counter metrics via SignalMetrics
  - Forced test-signal fallback after 30 min silence
  - ActivityMonitor: CRITICAL alerts for signal / trade inactivity
  - Execution-path logging on every simulated order attempt

Original Phase 10.4 description — LivePaperRunner: Real WS + Paper Execution Observation.

Connects to the live Polymarket WebSocket feed and runs the full trading
pipeline in PAPER mode using ExecutionSimulator (no real orders).

Pipeline::

    PolymarketWSClient (real WS)
        │  live orderbook / trade events
        ▼
    LivePaperRunner.event_loop
        │  data_received_ts stamped
        ▼
    OrderBookManager → Phase7MarketCache
        │  microstructure (bid/ask/spread/depth)
        ▼
    decision_callback (optional signal generator)
        │  signal_generated_ts stamped
        ▼
    RiskGuard.check()           ← kill switch / drawdown / daily loss
        │
    GoLiveController            ← forced PAPER mode (allow_execution always False)
        │  (blocks real orders — execution below is simulation only)
        ▼
    ExecutionSimulator.execute()  ← PAPER_LIVE_SIM — orderbook walk fill
        │  fill + slippage recorded in FillTracker
        ▼
    MetricsValidator  (latency, EV, fill_rate, drawdown, slippage)
        │
    TelegramLive  (error / kill / checkpoint alerts)

Background tasks:
    Checkpoint loop — sends Telegram summary at configured intervals (6h/12h/24h)
    Health log      — structured metrics log every health_log_interval_s
    WS reconnect    — handled transparently by PolymarketWSClient + logged

Constraints:
    - ZERO real order execution (ExecutionSimulator.send_real_orders=False enforced)
    - NO bypass risk guard
    - NO crash allowed (all exceptions caught/logged)
    - Deterministic shutdown via stop() or RunController

Usage::

    runner = LivePaperRunner.from_config(config, market_ids=["0xabc..."])
    await runner.start()
    await runner.run()          # blocks until stop() called or 24H elapsed
    report = runner.build_report()

Environment variables:
    CLOB_WS_URL          — WS endpoint (default: wss://clob.polymarket.com)
    TELEGRAM_BOT_TOKEN   — Telegram Bot API token
    TELEGRAM_CHAT_ID     — Telegram target chat ID
    DRY_RUN              — force paper mode ("true")
"""
from __future__ import annotations

import asyncio
import os
import time
import uuid
from dataclasses import dataclass, field
from typing import Callable, Optional

import structlog

from ..execution.fill_tracker import FillTracker
from ..execution.simulator import ExecutionSimulator, SimResult
from ..phase10.execution_guard import ExecutionGuard
from ..phase10.go_live_controller import GoLiveController, TradingMode
from ..phase7.analytics.execution_feedback import ExecutionFeedbackTracker
from ..phase7.analytics.latency_tracker import LatencyTracker
from ..phase7.analytics.trade_flow import TradeFlowAnalyzer
from ..phase7.engine.market_cache_patch import Phase7MarketCache
from ..phase7.engine.orderbook import OrderBookManager
from ..phase7.infra.ws_client import PolymarketWSClient, WSEvent
from ..phase8.risk_guard import RiskGuard
from ..phase9.metrics_validator import MetricsValidator
from ..phase9.telegram_live import TelegramLive
from ..monitoring.activity_monitor import ActivityMonitor
from ..monitoring.signal_metrics import SignalMetrics, SkipReason
from ..signal.signal_engine import SignalEngine

log = structlog.get_logger()

# ── Defaults ──────────────────────────────────────────────────────────────────

_DEFAULT_WS_URL = "wss://clob.polymarket.com"
_DEFAULT_HEALTH_LOG_S: float = 60.0
_DEFAULT_CHECKPOINT_INTERVALS: tuple[float, ...] = tuple(
    h * 3600.0 for h in range(1, 25)  # hourly: 1h … 24h (24 checkpoints)
)
_STALE_DATA_THRESHOLD_S: float = 5.0
_DEPTH_LEVELS: int = 5
_SLIPPAGE_THRESHOLD_BPS: float = 50.0
_ACTIVITY_ALERT_WINDOW_S: float = 3600.0  # 1 hour → CRITICAL inactivity alert


# ── Metrics snapshot ──────────────────────────────────────────────────────────


@dataclass
class PaperObservationSnapshot:
    """Point-in-time snapshot of live paper observation metrics.

    Attributes:
        elapsed_s: Seconds since run start.
        event_count: Total WS events processed.
        signal_count: Total signals generated by decision_callback.
        sim_order_count: Total simulated orders submitted.
        fill_count: Total simulated fills (full + partial).
        ws_reconnect_count: WS reconnect events observed.
        ev_capture_ratio: Actual / expected EV ratio.
        fill_rate: fill_count / sim_order_count.
        p95_latency_ms: 95th-percentile pipeline latency.
        drawdown: Current peak-to-trough drawdown.
        avg_slippage_bps: Average simulated slippage.
        p95_slippage_bps: p95 simulated slippage.
        worst_slippage_bps: Worst observed simulated slippage.
        kill_switch_active: True if RiskGuard has been triggered.
    """

    elapsed_s: float = 0.0
    event_count: int = 0
    signal_count: int = 0
    sim_order_count: int = 0
    fill_count: int = 0
    ws_reconnect_count: int = 0
    ev_capture_ratio: float = 0.0
    fill_rate: float = 0.0
    p95_latency_ms: float = 0.0
    drawdown: float = 0.0
    avg_slippage_bps: float = 0.0
    p95_slippage_bps: float = 0.0
    worst_slippage_bps: float = 0.0
    kill_switch_active: bool = False


# ── LivePaperRunner ───────────────────────────────────────────────────────────


class LivePaperRunner:
    """Phase 10.4 live paper observation runner.

    Runs the full trading pipeline against real market data without sending
    any real orders.  ExecutionSimulator is always in PAPER_LIVE_SIM mode;
    GoLiveController is always locked to PAPER mode.

    Thread-safety: single asyncio event loop only.
    """

    def __init__(
        self,
        ws_client: PolymarketWSClient,
        orderbook_manager: OrderBookManager,
        market_cache: Phase7MarketCache,
        trade_flow_analyzer: TradeFlowAnalyzer,
        simulator: ExecutionSimulator,
        fill_tracker: FillTracker,
        latency_tracker: LatencyTracker,
        feedback_tracker: ExecutionFeedbackTracker,
        go_live_controller: GoLiveController,
        execution_guard: ExecutionGuard,
        metrics_validator: MetricsValidator,
        risk_guard: RiskGuard,
        telegram: TelegramLive,
        market_ids: list[str],
        decision_callback: Optional[Callable] = None,
        health_log_interval_s: float = _DEFAULT_HEALTH_LOG_S,
        checkpoint_intervals_s: tuple[float, ...] = _DEFAULT_CHECKPOINT_INTERVALS,
        depth_levels: int = _DEPTH_LEVELS,
        signal_metrics: Optional[SignalMetrics] = None,
        signal_debug_mode: Optional[bool] = None,
    ) -> None:
        """Initialise the live paper runner.

        Args:
            ws_client: Configured PolymarketWSClient (real WS endpoint).
            orderbook_manager: Manages OrderBook instances per market.
            market_cache: Phase7MarketCache for live microstructure.
            trade_flow_analyzer: Trade flow imbalance tracker.
            simulator: ExecutionSimulator in PAPER_LIVE_SIM mode.
            fill_tracker: FillTracker for simulated fill records.
            latency_tracker: LatencyTracker for API RTT recording.
            feedback_tracker: ExecutionFeedbackTracker.
            go_live_controller: GoLiveController locked to PAPER mode.
            execution_guard: ExecutionGuard for pre-trade validation.
            metrics_validator: MetricsValidator for accumulating stats.
            risk_guard: RiskGuard for kill switch / drawdown / loss checks.
            telegram: TelegramLive for alert dispatch.
            market_ids: Polymarket condition IDs to observe.
            decision_callback: Optional async callable
                ``(market_id: str, ctx: dict) -> dict | None``.
                Should return a dict with keys: side, price, size_usd,
                expected_ev (optional).  Return None to skip this tick.
            health_log_interval_s: Seconds between structured health log lines.
            checkpoint_intervals_s: Tuple of elapsed seconds at which to send
                Telegram checkpoint summaries.
            depth_levels: Orderbook depth levels to aggregate.
            signal_metrics: Optional SignalMetrics instance; created internally
                if not provided.
            signal_debug_mode: Override SIGNAL_DEBUG_MODE env var for the
                embedded SignalEngine.  None means read from env.
        """
        # Enforce PAPER mode — this is non-negotiable for Phase 10.4
        if go_live_controller.mode is not TradingMode.PAPER:
            log.warning(
                "live_paper_runner_forcing_paper_mode",
                previous_mode=go_live_controller.mode.value,
            )
            go_live_controller.set_mode(TradingMode.PAPER)

        # Enforce simulator paper mode
        if getattr(simulator, "_send_real_orders", False):
            raise ValueError(
                "LivePaperRunner requires ExecutionSimulator with "
                "send_real_orders=False"
            )

        self._ws = ws_client
        self._books = orderbook_manager
        self._cache = market_cache
        self._flow = trade_flow_analyzer
        self._simulator = simulator
        self._fill_tracker = fill_tracker
        self._latency_tracker = latency_tracker
        self._feedback = feedback_tracker
        self._go_live = go_live_controller
        self._guard = execution_guard
        self._metrics = metrics_validator
        self._risk = risk_guard
        self._telegram = telegram
        self._market_ids = market_ids
        self._health_log_interval = health_log_interval_s
        self._checkpoint_intervals = sorted(checkpoint_intervals_s)
        self._depth_levels = depth_levels

        # ── Phase 10.8: Signal metrics & debug engine ─────────────────────────
        self._signal_metrics: SignalMetrics = signal_metrics or SignalMetrics()

        if decision_callback is not None:
            self._decision_callback: Optional[Callable] = SignalEngine(
                decision_callback=decision_callback,
                signal_metrics=self._signal_metrics,
                debug_mode=signal_debug_mode,
            )
        else:
            self._decision_callback = None

        # ── Phase 10.8: Activity monitor ──────────────────────────────────────
        self._activity_monitor: ActivityMonitor = ActivityMonitor(
            telegram=telegram,
            signal_source=lambda: self._signal_count,
            order_source=lambda: self._sim_order_count,
            alert_window_s=_ACTIVITY_ALERT_WINDOW_S,
        )

        # Runtime counters
        self._running: bool = False
        self._start_ts: float = 0.0
        self._event_count: int = 0
        self._signal_count: int = 0
        self._sim_order_count: int = 0
        self._fill_count: int = 0
        self._ws_reconnect_count: int = 0
        self._checkpoints_sent: set[float] = set()

        log.info(
            "live_paper_runner_initialized",
            mode="PAPER",
            market_count=len(market_ids),
            checkpoint_intervals_s=list(checkpoint_intervals_s),
        )

    # ── Factory ───────────────────────────────────────────────────────────────

    @classmethod
    def from_config(
        cls,
        cfg: dict,
        market_ids: list[str],
        decision_callback: Optional[Callable] = None,
    ) -> "LivePaperRunner":
        """Build runner from a top-level config dict.

        Args:
            cfg: Config dict (loaded from YAML or constructed in code).
            market_ids: Polymarket condition IDs to subscribe to.
            decision_callback: Optional async order-decision callable.

        Returns:
            Fully-configured LivePaperRunner.
        """
        ws_cfg = cfg.get("websocket", {})
        metrics_cfg = cfg.get("metrics", {})
        risk_cfg = cfg.get("risk", {})

        # Always use PAPER mode
        ws_url = os.getenv("CLOB_WS_URL", ws_cfg.get("url", _DEFAULT_WS_URL))
        ws_client = PolymarketWSClient(
            market_ids=market_ids,
            ws_url=ws_url,
            api_key=os.getenv("CLOB_API_KEY"),
            heartbeat_timeout_s=float(ws_cfg.get("heartbeat_timeout_s", 30.0)),
            reconnect_base_delay=float(ws_cfg.get("reconnect_base_delay_s", 1.0)),
            reconnect_max_delay=float(ws_cfg.get("reconnect_max_delay_s", 60.0)),
        )

        pos_cfg = cfg.get("position", {})
        market_cache = Phase7MarketCache(
            default_vol=float(pos_cfg.get("default_vol", 0.02)),
        )

        fill_tracker = FillTracker()
        simulator = ExecutionSimulator(
            fill_tracker=fill_tracker,
            slippage_threshold_bps=float(
                cfg.get("execution_simulator", {}).get(
                    "slippage_threshold_bps", _SLIPPAGE_THRESHOLD_BPS
                )
            ),
            send_real_orders=False,  # Non-negotiable: always paper
        )

        go_live_controller = GoLiveController(
            mode=TradingMode.PAPER,
            max_capital_usd=float(cfg.get("go_live", {}).get("max_capital_usd", 10_000.0)),
            max_trades_per_day=int(cfg.get("go_live", {}).get("max_trades_per_day", 200)),
        )

        execution_guard = ExecutionGuard.from_config(cfg)
        metrics_validator = MetricsValidator.from_config(cfg)

        risk_guard = RiskGuard(
            daily_loss_limit=float(risk_cfg.get("daily_loss_limit", -2000.0)),
            max_drawdown_pct=float(risk_cfg.get("max_drawdown_pct", 0.08)),
        )

        telegram = TelegramLive.from_env()

        # Checkpoint intervals from config or defaults
        raw_intervals = cfg.get("paper_observation", {}).get(
            "checkpoint_intervals_s",
            list(_DEFAULT_CHECKPOINT_INTERVALS),
        )
        checkpoint_intervals = tuple(float(v) for v in raw_intervals)

        return cls(
            ws_client=ws_client,
            orderbook_manager=OrderBookManager(),
            market_cache=market_cache,
            trade_flow_analyzer=TradeFlowAnalyzer(
                window_size=int(cfg.get("trade_flow", {}).get("window", 100))
            ),
            simulator=simulator,
            fill_tracker=fill_tracker,
            latency_tracker=LatencyTracker(),
            feedback_tracker=ExecutionFeedbackTracker(),
            go_live_controller=go_live_controller,
            execution_guard=execution_guard,
            metrics_validator=metrics_validator,
            risk_guard=risk_guard,
            telegram=telegram,
            market_ids=market_ids,
            decision_callback=decision_callback,
            health_log_interval_s=float(
                metrics_cfg.get("health_log_interval_s", _DEFAULT_HEALTH_LOG_S)
            ),
            checkpoint_intervals_s=checkpoint_intervals,
            depth_levels=int(ws_cfg.get("depth_levels", _DEPTH_LEVELS)),
            signal_debug_mode=cfg.get("signal_debug", {}).get("enabled"),
        )

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    async def start(self) -> None:
        """Start Telegram worker and prepare for run().

        Raises:
            RuntimeError: If ``TelegramLive`` is disabled (missing credentials).
                The 24H live paper observation requires Telegram monitoring.
        """
        if not self._telegram.enabled:
            raise RuntimeError(
                "TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID not configured. "
                "24H live paper observation requires Telegram monitoring. "
                "Set the env vars and restart."
            )
        await self._telegram.start()
        log.info("live_paper_runner_telegram_started")

    async def stop(self) -> None:
        """Gracefully stop the pipeline, activity monitor, and flush Telegram alerts."""
        log.info("live_paper_runner_stopping")
        self._running = False
        self._activity_monitor.stop()
        await self._ws.disconnect()
        await self._telegram.stop()
        log.info("live_paper_runner_stopped")

    # ── Main run loop ─────────────────────────────────────────────────────────

    async def run(self) -> None:
        """Start the Phase 10.4 live paper observation event loop.

        Connects to the real WS, processes events through the full pipeline,
        and runs until stop() is called or a critical unrecoverable error.

        Raises:
            No exceptions — all errors are caught, logged, and alerted.
        """
        self._running = True
        self._start_ts = time.time()
        run_id = str(uuid.uuid4())[:8]

        log.info(
            "live_paper_runner_run_starting",
            run_id=run_id,
            market_count=len(self._market_ids),
            market_ids=self._market_ids,
            mode="PAPER",
        )

        try:
            await self._ws.connect()
        except Exception as exc:  # noqa: BLE001
            log.error("live_paper_runner_ws_connect_failed", error=str(exc))
            await self._telegram.alert_error(
                str(exc), context="live_paper_runner_ws_connect"
            )
            self._running = False
            return

        background_tasks = [
            asyncio.create_task(
                self._health_log_loop(), name="lp_health_log"
            ),
            asyncio.create_task(
                self._checkpoint_loop(), name="lp_checkpoint"
            ),
            asyncio.create_task(
                self._activity_monitor.run(), name="lp_activity_monitor"
            ),
        ]

        try:
            async for event in self._ws.events():
                if not self._running:
                    break

                # Kill switch fast path
                if self._risk.disabled:
                    log.warning("live_paper_runner_kill_switch_active_skip_event")
                    break

                await self._handle_event(event)

        except asyncio.CancelledError:
            log.info("live_paper_runner_cancelled", run_id=run_id)

        except Exception as exc:  # noqa: BLE001
            log.error(
                "live_paper_runner_critical_error",
                error=str(exc),
                run_id=run_id,
                exc_info=True,
            )
            await self._telegram.alert_error(
                str(exc), context="live_paper_runner_critical_error"
            )

        finally:
            self._running = False
            for task in background_tasks:
                task.cancel()
                try:
                    await task
                except asyncio.CancelledError:
                    pass
            await self._ws.disconnect()
            log.info(
                "live_paper_runner_run_finished",
                run_id=run_id,
                elapsed_s=round(time.time() - self._start_ts, 1),
                total_events=self._event_count,
                total_signals=self._signal_count,
                total_sim_orders=self._sim_order_count,
                total_fills=self._fill_count,
                ws_reconnects=self._ws_reconnect_count,
            )

    # ── Event routing ─────────────────────────────────────────────────────────

    async def _handle_event(self, event: WSEvent) -> None:
        """Route a WS event to the appropriate handler.

        Args:
            event: Incoming WSEvent (orderbook or trade).
        """
        self._event_count += 1

        if event.type == "orderbook":
            await self._handle_orderbook_event(event)
        elif event.type == "trade":
            await self._handle_trade_event(event)
        else:
            log.debug("live_paper_runner_unknown_event_type", event_type=event.type)

    async def _handle_orderbook_event(self, event: WSEvent) -> None:
        """Process an orderbook snapshot or delta through the full pipeline.

        Pipeline:
          1. Stamp data_received_ts.
          2. Apply to OrderBookManager.
          3. Update Phase7MarketCache.
          4. Stale-data guard.
          5. Invoke decision_callback if present.
          6. If signal → ExecutionGuard → Simulator.
        """
        data_received_ts = time.time()
        market_id = event.market_id

        self._books.apply_ws_event(event.type, market_id, event.data, event.timestamp)

        snap = self._books.snapshot(market_id, self._depth_levels)
        if snap is None:
            log.debug("live_paper_runner_orderbook_not_ready", market_id=market_id)
            self._books.request_resync(market_id)
            return

        self._cache.on_orderbook_update(snap)

        if self._cache.is_stale(market_id, _STALE_DATA_THRESHOLD_S):
            log.warning(
                "live_paper_runner_stale_market_data",
                market_id=market_id,
                threshold_s=_STALE_DATA_THRESHOLD_S,
            )
            return

        if self._decision_callback is None or not snap.is_valid:
            return

        market_ctx = self._cache.get_market_context(market_id)
        market_ctx["orderbook_valid"] = snap.is_valid
        market_ctx["flow_imbalance"] = self._cache.get_trade_flow_imbalance(market_id)

        # Build orderbook dict for simulator from the WS event data.
        # The event data carries the cumulative bids/asks after
        # OrderBook.apply_ws_event() so this is the freshest view.
        raw_bids = event.data.get("bids", [])
        raw_asks = event.data.get("asks", [])
        market_ctx["orderbook"] = {
            "bids": [[float(b[0]), float(b[1])] for b in raw_bids if len(b) >= 2],
            "asks": [[float(a[0]), float(a[1])] for a in raw_asks if len(a) >= 2],
        }

        try:
            signal = await self._decision_callback(market_id, market_ctx)
            signal_generated_ts = time.time()
        except Exception as exc:  # noqa: BLE001
            log.error(
                "live_paper_runner_decision_callback_error",
                market_id=market_id,
                error=str(exc),
                exc_info=True,
            )
            await self._telegram.alert_error(
                str(exc), context=f"decision_callback:{market_id}"
            )
            return

        if signal is None:
            return

        self._signal_count += 1

        await self._simulate_order(
            market_id=market_id,
            signal=signal,
            market_ctx=market_ctx,
            data_received_ts=data_received_ts,
            signal_generated_ts=signal_generated_ts,
        )

    async def _handle_trade_event(self, event: WSEvent) -> None:
        """Update TradeFlowAnalyzer and MarketCache from a trade event."""
        market_id = event.market_id
        data = event.data
        price = float(data.get("price", 0.0))
        size = float(data.get("size", 0.0))
        side = str(data.get("side", "UNKNOWN"))

        self._flow.on_trade(
            market_id=market_id,
            price=price,
            size=size,
            side=side,
            timestamp=event.timestamp,
        )
        self._cache.on_trade(
            market_id=market_id,
            price=price,
            size=size,
            side=side,
            timestamp=event.timestamp,
        )

    # ── Simulated order execution ─────────────────────────────────────────────

    async def _simulate_order(
        self,
        market_id: str,
        signal: dict,
        market_ctx: dict,
        data_received_ts: float,
        signal_generated_ts: float,
    ) -> Optional[SimResult]:
        """Run pre-trade validation and simulate order execution.

        Args:
            market_id: Target Polymarket condition ID.
            signal: Signal dict with keys: side, price, size_usd,
                    expected_ev (optional).
            market_ctx: Current market context.
            data_received_ts: Unix timestamp when WS event arrived.
            signal_generated_ts: Unix timestamp when signal was produced.

        Returns:
            SimResult if simulation ran, None if blocked by guard/risk.
        """
        side = str(signal.get("side", "YES"))
        price = float(signal.get("price", 0.0))
        size_usd = float(signal.get("size_usd", 0.0))
        expected_ev = float(signal.get("expected_ev", 0.0))

        if size_usd <= 0 or price <= 0:
            log.warning(
                "live_paper_runner_invalid_signal",
                market_id=market_id,
                side=side,
                price=price,
                size_usd=size_usd,
            )
            return None

        # ── Risk guard check ──────────────────────────────────────────────────
        if self._risk.disabled:
            log.warning(
                "live_paper_runner_blocked_kill_switch",
                market_id=market_id,
            )
            self._metrics.record_fill(filled=False)
            return None

        # Daily loss / drawdown checks (paper mode: no real PnL tracked)
        # RiskGuard requires current_pnl to check against daily_loss_limit.
        # In PAPER mode the pipeline has no real losses so we pass 0.0.
        current_pnl = 0.0
        await self._risk.check_daily_loss(current_pnl)
        if self._risk.disabled:
            await self._telegram.alert_kill(reason="daily_loss_limit_breached_paper")
            self._metrics.record_fill(filled=False)
            return None

        # ── ExecutionGuard pre-trade validation ───────────────────────────────
        liquidity_usd = float(market_ctx.get("depth", 0.0))
        spread = float(market_ctx.get("spread", 0.02))
        slippage_pct = spread * 0.5

        guard_sig = (
            f"{market_id}:{side}:{round(price, 4)}:{round(size_usd, 2)}"
        )
        validation = self._guard.validate(
            market_id=market_id,
            side=side,
            price=price,
            size_usd=size_usd,
            liquidity_usd=liquidity_usd,
            slippage_pct=slippage_pct,
            order_guard_signature=guard_sig,
        )

        if not validation.passed:
            log.debug(
                "live_paper_runner_guard_rejected",
                market_id=market_id,
                reason=validation.reason,
            )
            # Map validation reason string to a structured SkipReason.
            # Check the most specific reasons first; fall back to RISK_BLOCK.
            reason_lower = (validation.reason or "").lower()
            if "duplicate" in reason_lower:
                skip_reason = SkipReason.DUPLICATE
            elif "liquidity" in reason_lower:
                skip_reason = SkipReason.LOW_LIQUIDITY
            else:
                skip_reason = SkipReason.RISK_BLOCK
            self._signal_metrics.record_skip(skip_reason)
            self._metrics.record_fill(filled=False)
            return None

        # ── Simulate execution ────────────────────────────────────────────────
        log.info(
            "live_paper_runner_execution_attempt",
            market_id=market_id,
            side=side,
            price=price,
            size_usd=size_usd,
            is_debug_signal=signal.get("is_debug_signal", False),
        )
        order_sent_ts = time.time()
        self._sim_order_count += 1

        orderbook = market_ctx.get("orderbook")
        sim_result = await self._simulator.execute(
            market_id=market_id,
            side=side,
            expected_price=price,
            size_usd=size_usd,
            orderbook=orderbook,
        )

        fill_received_ts = time.time()
        total_latency_ms = (fill_received_ts - data_received_ts) * 1000.0

        # ── Metrics recording ─────────────────────────────────────────────────
        self._metrics.record_latency(total_latency_ms)
        filled = sim_result.success
        if filled:
            self._fill_count += 1
        self._metrics.record_fill(filled=filled)

        if filled and sim_result.simulated_price > 0:
            mid = float(market_ctx.get("mid", price))
            actual_ev = sim_result.filled_size * abs(mid - sim_result.simulated_price)
            self._metrics.record_ev_signal(
                expected_ev=expected_ev, actual_ev=actual_ev
            )
            self._metrics.record_pnl_sample(cumulative_pnl=actual_ev)
        else:
            self._metrics.record_ev_signal(expected_ev=expected_ev, actual_ev=0.0)
            self._metrics.record_pnl_sample(cumulative_pnl=0.0)

        if filled and sim_result.slippage_bps != 0:
            self._metrics.record_slippage(sim_result.slippage_bps)

        # Latency spike alert
        if total_latency_ms > 1_000.0:
            log.warning(
                "live_paper_runner_latency_spike",
                market_id=market_id,
                latency_ms=round(total_latency_ms, 1),
            )
            await self._telegram.alert_error(
                f"latency_spike:{total_latency_ms:.0f}ms",
                context=f"market:{market_id}",
            )

        # Slippage spike alert
        if filled and sim_result.slippage_bps > _SLIPPAGE_THRESHOLD_BPS:
            log.warning(
                "live_paper_runner_slippage_spike",
                market_id=market_id,
                slippage_bps=round(sim_result.slippage_bps, 2),
                threshold=_SLIPPAGE_THRESHOLD_BPS,
            )
            await self._telegram.alert_error(
                f"slippage_spike:{sim_result.slippage_bps:.1f}bps",
                context=f"market:{market_id}",
            )

        log.info(
            "live_paper_runner_sim_order_executed",
            market_id=market_id,
            side=side,
            price=price,
            size_usd=size_usd,
            filled=filled,
            simulated_price=sim_result.simulated_price,
            filled_size=sim_result.filled_size,
            slippage_bps=sim_result.slippage_bps,
            latency_ms=round(total_latency_ms, 2),
            is_paper=True,
        )

        return sim_result

    # ── Background: health log ────────────────────────────────────────────────

    async def _health_log_loop(self) -> None:
        """Periodically emit a structured metrics health log."""
        while self._running:
            await asyncio.sleep(self._health_log_interval)
            if not self._running:
                break
            snap = self.snapshot()
            sig_snap = self._signal_metrics.snapshot()
            log.info(
                "live_paper_runner_health",
                elapsed_s=round(snap.elapsed_s, 0),
                event_count=snap.event_count,
                signal_count=snap.signal_count,
                sim_order_count=snap.sim_order_count,
                fill_count=snap.fill_count,
                fill_rate=round(snap.fill_rate, 4),
                p95_latency_ms=round(snap.p95_latency_ms, 1),
                avg_slippage_bps=round(snap.avg_slippage_bps, 2),
                drawdown=round(snap.drawdown, 4),
                ws_reconnects=snap.ws_reconnect_count,
                kill_switch_active=snap.kill_switch_active,
                total_signals_generated=sig_snap.total_generated,
                total_signals_skipped=sig_snap.total_skipped,
            )

    # ── Background: checkpoint loop ───────────────────────────────────────────

    async def _checkpoint_loop(self) -> None:
        """Send Telegram checkpoint summary at configured elapsed intervals."""
        while self._running:
            await asyncio.sleep(60.0)  # poll every minute
            if not self._running:
                break
            elapsed = time.time() - self._start_ts
            for interval in self._checkpoint_intervals:
                if interval not in self._checkpoints_sent and elapsed >= interval:
                    self._checkpoints_sent.add(interval)
                    await self._send_checkpoint(interval)

    async def _send_checkpoint(self, elapsed_s: float) -> None:
        """Send a Telegram checkpoint summary for the given elapsed time.

        Args:
            elapsed_s: Elapsed seconds threshold that triggered this checkpoint.
        """
        hours = elapsed_s / 3600.0
        snap = self.snapshot()
        metrics = self._metrics.compute()

        msg_lines = [
            f"⏱ *{hours:.0f}H CHECKPOINT — PAPER OBSERVATION*",
            f"Events: `{snap.event_count}` | Signals: `{snap.signal_count}`",
            f"Sim Orders: `{snap.sim_order_count}` | Fills: `{snap.fill_count}`",
            f"Fill Rate: `{snap.fill_rate:.1%}` | p95 Lat: `{snap.p95_latency_ms:.0f}ms`",
            f"Avg Slip: `{snap.avg_slippage_bps:.1f}bps` | "
            f"Worst Slip: `{snap.worst_slippage_bps:.1f}bps`",
            f"Drawdown: `{snap.drawdown:.2%}` | EV Ratio: `{snap.ev_capture_ratio:.2f}`",
            f"WS Reconnects: `{snap.ws_reconnect_count}`",
            f"Kill Switch: `{'ACTIVE' if snap.kill_switch_active else 'OFF'}`",
            f"GO-LIVE Ready: `{'YES ✅' if metrics.go_live_ready else 'NO ❌'}`",
        ]

        await self._telegram.alert_error(
            error="\n".join(msg_lines),
            context=f"checkpoint_{hours:.0f}h",
        )

        log.info(
            "live_paper_runner_checkpoint_sent",
            elapsed_h=hours,
            fill_rate=snap.fill_rate,
            p95_latency_ms=snap.p95_latency_ms,
            go_live_ready=metrics.go_live_ready,
        )

    # ── Metrics / reporting ───────────────────────────────────────────────────

    def snapshot(self) -> PaperObservationSnapshot:
        """Return a real-time metrics snapshot.

        Returns:
            PaperObservationSnapshot with current counters and computed metrics.
        """
        elapsed = time.time() - self._start_ts if self._start_ts else 0.0
        metrics = self._metrics.compute()

        # Sync WS reconnect count from client stats
        try:
            ws_stats = self._ws.stats()
            self._ws_reconnect_count = getattr(ws_stats, "reconnects", self._ws_reconnect_count)
        except Exception:  # noqa: BLE001
            pass

        return PaperObservationSnapshot(
            elapsed_s=elapsed,
            event_count=self._event_count,
            signal_count=self._signal_count,
            sim_order_count=self._sim_order_count,
            fill_count=self._fill_count,
            ws_reconnect_count=self._ws_reconnect_count,
            ev_capture_ratio=metrics.ev_capture_ratio,
            fill_rate=metrics.fill_rate,
            p95_latency_ms=metrics.p95_latency,
            drawdown=metrics.drawdown,
            avg_slippage_bps=metrics.avg_slippage_bps,
            p95_slippage_bps=metrics.p95_slippage_bps,
            worst_slippage_bps=metrics.worst_slippage_bps,
            kill_switch_active=self._risk.disabled,
        )

    def build_report(self) -> dict:
        """Build a structured final report dict for the observation run.

        Returns:
            Dict with runtime_summary, metrics_table, latency_stats,
            slippage_stats, ws_stability, risk_compliance, and
            go_live_readiness sections.
        """
        snap = self.snapshot()
        metrics = self._metrics.compute()

        go_live_ready = (
            metrics.ev_capture_ratio >= 0.75
            and metrics.fill_rate >= 0.60
            and metrics.p95_latency <= 500.0
            and metrics.drawdown <= 0.08
            and not snap.kill_switch_active
        )

        return {
            "phase": "10.8",
            "mode": "PAPER",
            "runtime_summary": {
                "elapsed_s": round(snap.elapsed_s, 1),
                "total_events": snap.event_count,
                "total_signals": snap.signal_count,
                "total_sim_orders": snap.sim_order_count,
                "total_fills": snap.fill_count,
                "ws_reconnects": snap.ws_reconnect_count,
            },
            "signal_metrics": self._signal_metrics.snapshot().to_dict(),
            "metrics_table": {
                "ev_capture_ratio": round(metrics.ev_capture_ratio, 4),
                "fill_rate": round(metrics.fill_rate, 4),
                "total_trades": metrics.total_trades,
            },
            "latency_stats": {
                "p95_latency_ms": round(metrics.p95_latency, 2),
                "sample_count": metrics.total_trades,
            },
            "slippage_stats": {
                "avg_slippage_bps": round(metrics.avg_slippage_bps, 2),
                "p95_slippage_bps": round(metrics.p95_slippage_bps, 2),
                "worst_slippage_bps": round(metrics.worst_slippage_bps, 2),
            },
            "ws_stability": {
                "reconnect_count": snap.ws_reconnect_count,
            },
            "risk_compliance": {
                "kill_switch_active": snap.kill_switch_active,
                "drawdown": round(metrics.drawdown, 4),
                "paper_mode_enforced": True,
                "real_orders_sent": False,
            },
            "go_live_readiness": "YES" if go_live_ready else "NO",
            "go_live_gate_details": metrics.gate_details,
        }
