"""System Activation Monitor — event/signal flow validation.

Tracks:
    - event_count: total WebSocket events received
    - signal_count: total signals generated by strategies
    - trade_count: total trades executed

Periodic logging (every 10s):
    "events=X signals=Y"

Assertions (every 60s):
    - If event_count == 0 after 60s → marks boot health as unhealthy
    - If event_count > 0 and signal_count == 0 after 60s → logs WARNING "NO SIGNAL GENERATED"
"""
from __future__ import annotations

import asyncio
import time
from typing import Optional

import structlog

log = structlog.get_logger()

_LOG_INTERVAL_S: float = 10.0
_ASSERT_INTERVAL_S: float = 60.0


class SystemActivationMonitor:
    """Monitors event and signal flow, logging and asserting liveness.

    Thread-safety: single asyncio event loop only.
    """

    def __init__(
        self,
        log_interval_s: float = _LOG_INTERVAL_S,
        assert_interval_s: float = _ASSERT_INTERVAL_S,
    ) -> None:
        self._log_interval = log_interval_s
        self._assert_interval = assert_interval_s

        self.event_count: int = 0
        self.signal_count: int = 0
        self.trade_count: int = 0
        self.ws_connected: bool = False

        self._running: bool = False
        self._log_task: Optional[asyncio.Task] = None
        self._assert_task: Optional[asyncio.Task] = None
        self._start_ts: float = 0.0
        self._boot_healthy: bool = True
        self._boot_health_reason: str = "pending"

    def is_boot_healthy(self) -> bool:
        """Return latest startup health state from assert loop."""
        return self._boot_healthy

    def boot_health_reason(self) -> str:
        """Return latest startup health reason code."""
        return self._boot_health_reason

    # ── Counters ──────────────────────────────────────────────────────────────

    def record_event(self) -> None:
        """Increment the event counter (call on each WS event received)."""
        self.event_count += 1

    def record_signal(self) -> None:
        """Increment the signal counter (call on each signal generated)."""
        self.signal_count += 1

    def record_trade(self) -> None:
        """Increment the trade counter (call on each trade executed)."""
        self.trade_count += 1

    def record_ws_state(self, connected: bool) -> None:
        """Update the current WebSocket connection state."""
        self.ws_connected = connected

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    async def start(self) -> None:
        """Start background logging and assertion tasks."""
        if self._running:
            return
        self._running = True
        self._start_ts = time.time()
        self._boot_healthy = True
        self._boot_health_reason = "pending"
        self._log_task = asyncio.create_task(
            self._log_loop(), name="activation_monitor_log"
        )
        self._assert_task = asyncio.create_task(
            self._assert_loop(), name="activation_monitor_assert"
        )
        log.info("system_activation_monitor_started")

    async def stop(self) -> None:
        """Stop background tasks."""
        self._running = False
        for task in (self._log_task, self._assert_task):
            if task and not task.done():
                task.cancel()
                try:
                    await task
                except asyncio.CancelledError:
                    pass
        log.info("system_activation_monitor_stopped")

    # ── Internal loops ────────────────────────────────────────────────────────

    async def _log_loop(self) -> None:
        """Log event/signal counts every log_interval_s seconds."""
        while self._running:
            await asyncio.sleep(self._log_interval)
            log.info(
                "activation_flow",
                events=self.event_count,
                signals=self.signal_count,
                trades=self.trade_count,
            )

    async def _assert_loop(self) -> None:
        """After assert_interval_s, validate liveness with controlled startup noise."""
        await asyncio.sleep(self._assert_interval)
        elapsed = time.time() - self._start_ts

        if self.event_count == 0:
            self._boot_healthy = False
            self._boot_health_reason = "no_events_received"
            log.error(
                "activation_boot_health_unhealthy",
                elapsed_s=round(elapsed, 1),
                event_count=self.event_count,
                signal_count=self.signal_count,
                hint="WebSocket feed may be disconnected or MARKET_IDS may be invalid",
            )
            return

        self._boot_healthy = True
        self._boot_health_reason = "healthy"

        if self.signal_count == 0:
            log.warning(
                "NO SIGNAL GENERATED",
                event_count=self.event_count,
                elapsed_s=round(elapsed, 1),
                hint="Check edge threshold, market liquidity, and strategy config",
            )
