"""System Activation Monitor — event/signal flow validation.

Tracks:
    - event_count: total WebSocket events received
    - signal_count: total signals generated by strategies
    - trade_count: total trades executed

Periodic logging (every 10s):
    "events=X signals=Y"

Assertions (every 60s):
    - If event_count == 0 after 60s → controlled error log (no background task leak)
    - If event_count > 0 and signal_count == 0 after 60s → logs WARNING "NO SIGNAL GENERATED"
"""
from __future__ import annotations

import asyncio
import time
from typing import Awaitable, Callable, Optional

import structlog

log = structlog.get_logger()

_LOG_INTERVAL_S: float = 10.0
_ASSERT_INTERVAL_S: float = 60.0


class SystemActivationMonitor:
    """Monitors event and signal flow, logging and asserting liveness.

    Thread-safety: single asyncio event loop only.
    """

    def __init__(
        self,
        log_interval_s: float = _LOG_INTERVAL_S,
        assert_interval_s: float = _ASSERT_INTERVAL_S,
    ) -> None:
        self._log_interval = log_interval_s
        self._assert_interval = assert_interval_s

        self.event_count: int = 0
        self.signal_count: int = 0
        self.trade_count: int = 0
        self.ws_connected: bool = False

        self._running: bool = False
        self._log_task: Optional[asyncio.Task] = None
        self._assert_task: Optional[asyncio.Task] = None
        self._start_ts: float = 0.0

    def record_event(self) -> None:
        self.event_count += 1

    def record_signal(self) -> None:
        self.signal_count += 1

    def record_trade(self) -> None:
        self.trade_count += 1

    def record_ws_state(self, connected: bool) -> None:
        self.ws_connected = connected

    async def start(self) -> None:
        if self._running:
            return
        self._running = True
        self._start_ts = time.time()
        self._log_task = asyncio.create_task(
            self._run_guarded(self._log_loop, task_name="activation_monitor_log"),
            name="activation_monitor_log",
        )
        self._assert_task = asyncio.create_task(
            self._run_guarded(self._assert_loop, task_name="activation_monitor_assert"),
            name="activation_monitor_assert",
        )
        log.info("system_activation_monitor_started")

    async def stop(self) -> None:
        self._running = False
        for task in (self._log_task, self._assert_task):
            if task and not task.done():
                task.cancel()
                try:
                    await task
                except asyncio.CancelledError:
                    pass
        log.info("system_activation_monitor_stopped")

    async def _run_guarded(self, runner: Callable[[], Awaitable[None]], *, task_name: str) -> None:
        try:
            await runner()
        except asyncio.CancelledError:
            raise
        except Exception as exc:
            log.error("system_activation_monitor_task_failed", task_name=task_name, error=str(exc))

    async def _log_loop(self) -> None:
        while self._running:
            await asyncio.sleep(self._log_interval)
            log.info(
                "activation_flow",
                events=self.event_count,
                signals=self.signal_count,
                trades=self.trade_count,
            )

    async def _assert_loop(self) -> None:
        await asyncio.sleep(self._assert_interval)
        elapsed = time.time() - self._start_ts

        if self.event_count == 0:
            raise RuntimeError(
                f"No events received after {round(elapsed, 1)}s — "
                "WebSocket feed may be disconnected or market IDs may be invalid. "
                "Check WebSocket connection status and verify MARKET_IDS are correct condition IDs."
            )

        if self.event_count > 0 and self.signal_count == 0:
            log.warning(
                "NO SIGNAL GENERATED",
                event_count=self.event_count,
                elapsed_s=round(elapsed, 1),
                hint="Check edge threshold, market liquidity, and strategy config",
            )
